# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

convolve_density <- function(f1, f2) {
    .Call(`_test_convolve_density`, f1, f2)
}

